version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    # - mnd
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    cyclop:
      max-complexity: 20
    revive:
      enable-all-rules: true
      rules:
        - name: var-naming
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: add-constant
          disabled: true
        - name: function-length
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: import-alias-naming
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: nested-structs
          disabled: true
        - name: empty-lines
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: use-any
          disabled: true
        - name: cyclomatic
          arguments: [15] # value could be decreased in the future, default = 10
        - name: unhandled-error
          arguments: ["fmt.Printf", "fmt.Println"]
        - name: cognitive-complexity
          arguments: [55] # value could be decreased in the future, default = 7. proxy.NewProxyMiddleware have 53
    gocritic:
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
        - singleCaseSwitch
        - ifElseChain
        - commentFormatting
        - commentedOutCode
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 15
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: _test\.go$
        linters:
          - cyclop
          - funlen
issues:
  max-issues-per-linter: 100
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
